Bug Fix PR
input-output-hk/wsc-poc pull request #33
Opened 2024-12-31 23:25 UTC by colll78

Fix a few miscellaneous bugs and remove some unnecessary checks.

The bugs mostly had to do with the credential validation within directory node datums.

2025-01-01 12:08 UTC, j-mueller commented
Looks ok to me, the tests don't compile though.

2025-01-01 12:08 UTC, j-mueller requested changes

2025-01-01 12:08 UTC, j-mueller commented on src/lib/SmartTokens/Contracts/ProgrammableLogicBase.hs
> +-- pcheckTransferLogic :: Term s (PAsData PCurrencySymbol :--> PBuiltinList (PAsData PTxInInfo) :--> PBuiltinList (PAsData PTokenProof) :--> PBuiltinList (PAsData PByteString) :--> PValue 'Sorted 'Po
Delete

2025-01-01 12:08 UTC, j-mueller commented on src/lib/SmartTokens/Types/PTokenDirectory.hs
> +      -- in ptraceInfo (pshow $ pmkBuiltinList [pforgetData expectedDirectoryNode]) $ outputNode #== expectedDirectoryNode
Delete

2025-01-01 12:08 UTC, j-mueller commented on src/lib/Wst/Offchain/Env.hs
> +withTransferFor :: MonadReader (CombinedEnv o d t r era) m => C.PaymentCredential -> C.Hash C.PaymentKey -> ReaderT (CombinedEnv o d Identity r era) m a -> m a
If you change the `d` parameter to `Identity` you could get the payment credential from `DirectoryEnv`.

2025-01-01 12:08 UTC, j-mueller commented on flake.nix
> +      "loony-tools:pr9m4BkM/5/eSTZlkQyRt57Jz7OMBxNSUiMC4FkcNfk="
What do we need this for?

2025-01-01 18:57 UTC, colll78 commented on flake.nix
> +      "loony-tools:pr9m4BkM/5/eSTZlkQyRt57Jz7OMBxNSUiMC4FkcNfk="
My nix was refusing to take some stuff from cache without it.

2025-01-01 20:39 UTC, j-mueller commented
Ok some of the tests fail with script errors now, maybe the tx building code needs to be adjusted?

2025-01-02 10:54 UTC, j-mueller approved these changes
LGTM Thank you!

2025-01-02 10:54 UTC, merged